site_name: VyHub Docs
site_url: https://docs.vyhub.net
nav:
  - Welcome: index.md
  - Quickstart: quickstart.md
  - Central:
    - central/general.md
    - central/instance.md
    - central/custom_domain.md
  - Guide:
    - guide/adverts.md
    - guide/authorization.md
    - guide/api.md
    - guide/ban.md
    - guide/customizability.md
    - guide/faq.md
    - guide/group.md
    - Import:
      - guide/import/general.md
      - guide/import/gextension.md
    - guide/legal.md
    - guide/navigation.md
    - guide/property.md
    - guide/requirement_set.md
    - guide/server.md
    - guide/serverbundle.md
    - Shop:
      - guide/shop/general.md
      - guide/shop/packet.md
      - guide/shop/payment_gateway.md
      - guide/shop/reward.md
      - guide/shop/tax.md
    - guide/user.md
    - guide/warning.md
  - Game Integrations:
    - game/discord.md
    - game/gmod.md
    - game/minecraft.md
  - For Developers:
    - dev/game_clients.md
  - Changelog: changelog.md
  - Roadmap: roadmap.md
theme:
  name: material
  palette:
    scheme: slate
    primary: red
  logo: assets/logo.svg
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
extra_css:
  - stylesheets/extra.css
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-CJW8RM10E1
plugins:
  - mike
  - search
